"use client";

import React, { useEffect, useState } from "react";
import Link from "next/link";
import { useParams } from "next/navigation";
import { CustodyEvent, Document } from "@/types";
import { apiRequest } from "@/lib/api";
import { CustodyTimeline } from "@/components/custody-timeline";
import { ArrowLeft, Printer, ShieldCheck, Download, CheckCircle2 } from "lucide-react";

export default function DocumentCustodyPage() {
  const { documentId } = useParams();
  const [doc, setDoc] = useState<Document | null>(null);
  const [events, setEvents] = useState<CustodyEvent[]>([]);
  const [loading, setLoading] = useState<boolean>(true);

  useEffect(() => {
    async function loadCustody() {
      if (!documentId) return;
      try {
        const [docData, eventsData] = await Promise.all([
          apiRequest<Document>(`/api/v1/documents/${documentId}`),
          apiRequest<CustodyEvent[]>(`/api/v1/documents/${documentId}/custody`),
        ]);
        setDoc(docData);
        setEvents(eventsData);
      } catch (err) {
        console.error("Custody load error:", err);
      } finally {
        setLoading(false);
      }
    }
    loadCustody();
  }, [documentId]);

  if (loading) {
    return <div className="p-12 text-center text-slate-400 font-mono">Loading chain of custody trail...</div>;
  }

  if (!doc) {
    return <div className="p-8 text-center text-slate-700">Document exhibit not found.</div>;
  }

  return (
    <div className="max-w-4xl mx-auto space-y-6 font-sans">
      <div className="flex items-center justify-between print:hidden">
        <Link
          href={`/documents/${documentId}`}
          className="text-xs font-semibold text-slate-500 hover:text-slate-800 flex items-center gap-1"
        >
          <ArrowLeft className="w-3.5 h-3.5" /> Back to Document Dossier
        </Link>
        <button
          onClick={() => window.print()}
          className="px-4 py-2 bg-slate-900 hover:bg-slate-800 text-white rounded-xl text-xs font-bold shadow-sm transition-all flex items-center gap-2"
        >
          <Printer className="w-4 h-4" /> Print Certified Custody Report
        </button>
      </div>

      <div className="bg-white rounded-2xl border border-slate-200 p-8 shadow-xs space-y-6">
        {/* Certified Certificate Header */}
        <div className="border-b-2 border-slate-900 pb-5 text-center space-y-1">
          <div className="inline-flex items-center gap-1.5 px-3 py-1 rounded-full bg-blue-50 text-blue-900 border border-blue-200 text-xs font-mono font-bold mb-2">
            <ShieldCheck className="w-4 h-4 text-blue-700" />
            GOVERNMENT EVIDENCE CERTIFICATION (SEC 65B)
          </div>
          <h1 className="text-xl font-bold uppercase tracking-tight text-slate-900">
            Chain of Custody & Cryptographic Integrity Certificate
          </h1>
          <p className="text-xs text-slate-500 font-mono">
            Generated by NyayRaksha Permissioned Ledger Platform (SIH 26190)
          </p>
        </div>

        {/* Exhibit & Case Dossier Summary */}
        <div className="bg-slate-50 rounded-xl p-4 border border-slate-200 grid grid-cols-2 sm:grid-cols-4 gap-4 font-mono text-xs">
          <div>
            <span className="text-slate-400 block">Exhibit Title:</span>
            <span className="font-bold text-slate-900">{doc.title}</span>
          </div>
          <div>
            <span className="text-slate-400 block">Case Docket:</span>
            <span className="font-bold text-blue-700">{doc.case_id}</span>
          </div>
          <div>
            <span className="text-slate-400 block">Classification:</span>
            <span className="font-bold text-slate-900">{doc.classification}</span>
          </div>
          <div>
            <span className="text-slate-400 block">Total Custody Events:</span>
            <span className="font-bold text-emerald-700">{events.length} Verified</span>
          </div>
        </div>

        {/* Timeline View */}
        <div className="pt-2">
          <h2 className="text-sm font-bold uppercase tracking-wider text-slate-800 font-mono mb-4">
            Chronological Custody & Event Ledger
          </h2>
          <CustodyTimeline events={events} />
        </div>

        {/* Attestation Footer */}
        <div className="pt-6 border-t border-slate-200 text-xs text-slate-500 font-mono flex flex-wrap items-center justify-between gap-4">
          <div>
            <p>Hash Integrity: Deterministic SHA-256 Verified</p>
            <p>Ledger Network: Hyperledger Fabric Consensus</p>
          </div>
          <div className="text-right">
            <p>Certified at: {new Date().toISOString()}</p>
            <p className="text-slate-400">Document Reference: {doc.id}</p>
          </div>
        </div>
      </div>
    </div>
  );
}
